In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [4]:
a=np.array([(1,2,3),(4,5,6)])

In [6]:
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
a.size

6

In [8]:
a.itemsize

4

In [9]:
a.itemsize * a.size

24

In [10]:
a.dtype

dtype('int32')

In [12]:
a.ndim

2

In [13]:
a.shape

(2, 3)

In [21]:
import sys
l=list(range(1000))
a=np.arange(1000,dtype="int8")
print("LIST SIZE:",sys.getsizeof(500)*len(l))
print("ARRAY SIZEL:",a.itemsize*a.size)

LIST SIZE: 28000
ARRAY SIZEL: 1000


In [26]:
import time

SIZE=1000000

L1=range(SIZE)
L2=range(SIZE)

A1=np.arange(SIZE)
A2=np.arange(SIZE)

start=time.time()
result=[x+y for x,y in zip(L1,L2)]
end=time.time()

print("LIST TOOK: ", (end-start)*1000)


start=time.time()
result=A1+A2
end=time.time()

print("ARRAY TOOK: ", (end-start)*1000)

LIST TOOK:  287.7230644226074
ARRAY TOOK:  27.20928192138672


In [27]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [29]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
a.shape

(3, 3)

In [31]:
a[1,1]

5

In [33]:
a[1,1:3]

array([5, 6])

In [35]:
print(a[1:3,1:3])

[[5 6]
 [8 9]]


In [36]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(a.sum())

45


In [38]:
print(a.sum(axis=0))

[12 15 18]


In [39]:
print(a.sum(axis=1))

[ 6 15 24]


In [40]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [42]:
np.std(a)

2.581988897471611

In [44]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [46]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [47]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [48]:
np.log(100)

4.605170185988092

In [49]:
np.log10(100)

2.0

In [50]:
np.log2(32)

5.0

In [54]:
np.log10(100000)

5.0

In [56]:
np.zeros((2,3), dtype='int32')

array([[0, 0, 0],
       [0, 0, 0]])

In [59]:
np.ones((3,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [60]:
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [61]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a+a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [64]:
a-a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [65]:
a/a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [67]:
np.dot(a,a)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [68]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])